import type { Config } from "tailwindcss";

import { screenBreakPoints } from "./src/ui/common/config/screen-breakpoints";

const coreUIConfig = require("@babylonlabs-io/core-ui/tailwind");

const config: Config = {
  presets: [coreUIConfig],
  content: ["./src/ui/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    screens: screenBreakPoints,
    extend: {
      colors: {
        blue: {
          50: "#67AAEE",
          200: "#1669BB",
          900: "#273852",
        },
        "gray-custom": {
          50: "#F7F8FA",
          150: "#F3F4F6",
          200: "#7A8AA0",
        },
        primary: {
          15: "var(--primary-15)",
          25: "var(--primary-25)",
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          150: "var(--primary-150)",
          200: "var(--primary-200)",
          250: "var(--primary-250)",
          270: "var(--primary-270)",
          300: "var(--primary-300)",
          350: "var(--primary-350)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          850: "var(--primary-850)",
          900: "var(--primary-900)",
          925: "var(--primary-925)",
          950: "var(--primary-950)",
          "disabled-light": "var(--primary-disabled-light)",
          "disabled-dark": "var(--primary-disabled-dark)",
        },
        gray: {
          50: "var(--gray-50)",
          75: "var(--gray-75)",
          100: "var(--gray-100)",
          150: "var(--gray-150)",
          200: "var(--gray-200)",
          300: "var(--gray-300)",
          350: "var(--gray-350)",
          400: "var(--gray-400)",
          500: "var(--gray-500)",
          550: "var(--gray-550)",
          600: "var(--gray-600)",
          650: "var(--gray-650)",
          700: "var(--gray-700)",
          725: "var(--gray-725)",
          750: "var(--gray-750)",
          765: "var(--gray-765)",
          775: "var(--gray-775)",
          800: "var(--gray-800)",
          825: "var(--gray-825)",
          850: "var(--gray-850)",
          875: "var(--gray-875)",
          900: "var(--gray-900)",
          925: "var(--gray-925)",
          950: "var(--gray-950)",
          975: "var(--gray-975)",
        },
        red: {
          50: "var(--red-50)",
          100: "var(--red-100)",
          200: "var(--red-200)",
          300: "var(--red-300)",
          350: "var(--red-350)",
          400: "var(--red-400)",
          500: "var(--red-500)",
          600: "var(--red-600)",
          700: "var(--red-700)",
          800: "var(--red-800)",
          850: "var(--red-850)",
          900: "var(--red-900)",
          950: "var(--red-950)",
        },
        green: {
          50: "var(--green-50)",
          100: "var(--green-100)",
          200: "var(--green-200)",
          300: "var(--green-300)",
          400: "var(--green-400)",
          500: "var(--green-500)",
          600: "var(--green-600)",
          700: "var(--green-700)",
          800: "var(--green-800)",
          850: "var(--green-850)",
          900: "var(--green-900)",
          950: "var(--green-950)",
        },
        orange: {
          50: "var(--orange-50)",
          100: "var(--orange-100)",
          200: "var(--orange-200)",
          300: "var(--orange-300)",
          400: "var(--orange-400)",
          500: "var(--orange-500)",
          600: "var(--orange-600)",
          700: "var(--orange-700)",
          800: "var(--orange-800)",
          900: "var(--orange-900)",
          950: "var(--orange-950)",
        },
        yellow: {
          50: "var(--yellow-50)",
          100: "var(--yellow-100)",
          200: "var(--yellow-200)",
          300: "var(--yellow-300)",
          400: "var(--yellow-400)",
          500: "var(--yellow-500)",
          600: "var(--yellow-600)",
          700: "var(--yellow-700)",
          800: "var(--yellow-800)",
          900: "var(--yellow-900)",
          950: "var(--yellow-950)",
        },
        background: {
          "bg-blue": "var(--background-bg-blue)",
          "bg-gray": "var(--background-bg-gray)",
        },

        disabled: {
          background: "var(--disabled-background)",
          text: "var(--disabled-text)",
          "background-primary": "var(--disabled-background-primary)",
        },

        blur: {
          white: "var(--blur-white)",
          black: "var(--blur-black)",
        },

        greyscale: {
          "surface-title": "var(--greyscale-surface-title)",
          "surface-subtle": "var(--greyscale-surface-subtle)",
          "surface-subtle-lighter": "var(--greyscale-surface-subtle-lighter)",
          "surface-subtle-hover": "var(--greyscale-surface-subtle-hover)",
          "surface-default": "var(--greyscale-surface-default)",
          "surface-default-darker": "var(--greyscale-surface-default-darker)",
          "surface-disabled": "var(--greyscale-surface-disabled)",
          "surface-disabled-darker": "var(--greyscale-surface-disabled-darker)",
          "bg-input": "var(--greyscale-bg-input)",

          "border-lighter": "var(--greyscale-border-lighter)",
          "border-default": "var(--greyscale-border-default)",
          "border-default-darker": "var(--greyscale-border-default-darker)",
          "border-disabled": "var(--greyscale-border-disabled)",
          "border-darker": "var(--greyscale-border-darker)",

          "text-btc-lock": "var(--greyscale-text-btc-lock)",
          "text-title": "var(--greyscale-text-title)",
          "text-body": "var(--greyscale-text-body)",
          "text-subtitle": "var(--greyscale-text-subtitle)",
          "text-caption": "var(--greyscale-text-caption)",
          "text-negative": "var(--greyscale-text-negative)",
          "text-disabled": "var(--greyscale-text-disabled)",
          "text-disabled-2": "var(--greyscale-text-disabled-2)",
        },

        option: {
          border: "var(--option-border)",
        },

        brand: {
          "surface-super-subtle": "var(--brand-surface-super-subtle)",
          "surface-hover-subtle": "var(--brand-surface-hover-subtle)",
          "surface-subtle": "var(--brand-surface-subtle)",
          "surface-badge": "var(--brand-surface-badge)",
          "surface-lighter": "var(--brand-surface-lighter)",
          "surface-default": "var(--brand-surface-default)",
          "surface-darker": "var(--brand-surface-darker)",
          "surface-op-sub": "var(--brand-surface-op-sub)",
          "surface-disabled": "var(--brand-surface-disabled)",

          "border-subtle": "var(--brand-border-subtle)",
          "border-lighter": "var(--brand-border-lighter)",
          "border-default": "var(--brand-border-default)",
          "border-darker": "var(--brand-border-darker)",

          "text-title": "var(--brand-text-title)",
          "text-body": "var(--brand-text-body)",
          "text-subtitle": "var(--brand-text-subtitle)",
          "text-caption": "var(--brand-text-caption)",
          "text-negative": "var(--brand-text-negative)",
          "text-disabled": "var(--brand-text-disabled)",
          "text-slide": "var(--brand-text-slide)",
        },

        error: {
          "surface-subtle": "var(--error-surface-subtle)",
          "surface-subtle-2": "var(--error-surface-subtle-2)",
          "surface-lighter": "var(--error-surface-lighter)",
          "surface-default": "var(--error-surface-default)",
          "surface-darker": "var(--error-surface-darker)",

          "border-subtle": "var(--error-border-subtle)",
          "border-lighter": "var(--error-border-lighter)",
          "border-default": "var(--error-border-default)",
          "border-darker": "var(--error-border-darker)",

          "text-title": "var(--error-text-title)",
          "text-body": "var(--error-text-body)",
          "text-subtitle": "var(--error-text-subtitle)",
          text: "var(--error-text)",
        },

        warning: {
          "surface-subtle": "var(--warning-surface-subtle)",
          "surface-lighter": "var(--warning-surface-lighter)",
          "surface-default": "var(--warning-surface-default)",
          "surface-darker": "var(--warning-surface-darker)",

          "border-subtle": "var(--warning-border-subtle)",
          "border-lighter": "var(--warning-border-lighter)",
          "border-default": "var(--warning-border-default)",
          "border-darker": "var(--warning-border-darker)",

          "text-title": "var(--warning-text-title)",
          "text-body": "var(--warning-text-body)",
          "text-subtitle": "var(--warning-text-subtitle)",
        },

        success: {
          "surface-subtle": "var(--success-surface-subtle)",
          "surface-subtle-darker": "var(--success-surface-subtle-darker)",
          "surface-lighter": "var(--success-surface-lighter)",
          "surface-default": "var(--success-surface-default)",
          "surface-darker": "var(--success-surface-darker)",

          "border-subtle": "var(--success-border-subtle)",
          "border-lighter": "var(--success-border-lighter)",
          "border-default": "var(--success-border-default)",
          "border-darker": "var(--success-border-darker)",

          "text-title": "var(--success-text-title)",
          "text-body": "var(--success-text-body)",
          "text-negative": "var(--success-text-negative)",
          "text-subtitle": "var(--success-text-subtitle)",
        },
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      fontFamily: {
        sans: ["Roboto", "sans-serif"],
        roboto: ["var(--font-roboto)", "sans-serif"],
        dmsans: ["var(--font-dmsans)", "sans-serif"],
        inter: ["var(--font-inter)", "sans-serif"],
        poppins: ["var(--font-poppins)", "sans-serif"],
      },
      backgroundSize: {
        "size-200": "200% 200%",
      },
      backgroundPosition: {
        "pos-0": "0% 0%",
        "pos-100": "100% 100%",
      },
    },
  },
};

export default config;
